version: '3.9'
services:
  readme.uploader.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.uploader.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: readme.uploader

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - readme.mongo.uploader:/data/db

  readme.uploader.mongo.ui:
    image: mongo-express:latest
    restart: always
    container_name: readme.uploader.mongo.ui
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readme.uploader.mongo:${MONGO_PORT}/

volumes:
  readme.mongo.uploader:
