version: '3.5'
services:
  readme.one.postgres:
    image: postgres:14-alpine
    container_name: readme.one.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: readme-one
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - readme.one.post:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - readme.post

  readme.one.pgadmin:
    image: dpage/pgadmin4
    container_name: readme.one.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "v4nkov.v@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - ${POSTGRES_PGADMIN_PORT}:80
    networks:
      - readme.post

volumes:
  readme.one.post:

networks:
  readme.post:
      driver: bridge
