version: '3.9'
services:
  readme.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: "readme.notify.fakesmtp"
    hostname: "fakesmtp"
    ports:
      - ${FAKE_SMTP_SERVER_PORT}:${FAKE_SMTP_SERVER_PORT}
      - 1083:${FAKE_SMTP_SERVER_UI_PORT}

  readme.notify.rabbitmq:
    image: rabbitmq:3.11-management
    container_name: readme.notify.rabbitmq
    ports:
      - 1088:15672
      - ${RABBIT_POST}:${RABBIT_POST}
    environment:
      RABBITMQ_DEFAULT_USER: ${MONGO_USER}
      RABBITMQ_DEFAULT_PASS: ${MONGO_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  readme.notify.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.notify.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: readme.notify

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - readme.notify.mongo:/data/db

  readme.notify.mongo.ui:
    image: mongo-express:latest
    restart: always
    container_name: readme.notify.mongo.ui
    ports:
      - ${MONGO_UI_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readme.uploader.mongo:${MONGO_PORT}/

volumes:
  readme.notify.mongo:
